# Generated by Django 3.1.7 on 2023-12-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bot_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='group_chat_id',
            field=models.TextField(null=True),
        ),
    ]
