# Generated by Django 5.0.4 on 2024-04-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_id_alter_card_id_alter_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_influencer',
            field=models.BooleanField(default=False),
        ),
    ]
