# Generated by Django 3.1.7 on 2025-07-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_auto_20250722_1339'),
        ('account', '0007_auto_20240516_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='leadpoles',
            field=models.ManyToManyField(blank=True, to='board.LeadPoles'),
        ),
    ]
