# Generated by Django 3.1.7 on 2025-07-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_leadpoles'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='zvonki_api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='zvonki_user_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
