# Generated by Django 3.1.7 on 2025-07-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20250724_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='zvonki_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
