# Generated by Django 4.2.23 on 2025-07-29 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_account_id_alter_card_id_alter_company_id_and_more'),
        ('account', '0010_company_zvonki_name'),
    ]

    operations = [
    ]
