# Generated by Django 3.1.7 on 2025-09-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20250803_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='group_id',
            field=models.TextField(null=True),
        ),
    ]
