# Generated by Django 3.1.7 on 2025-07-23 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0025_auto_20250723_1538'),
        ('main', '0003_auto_20240516_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('complaint', 'Complaint'), ('objection', 'Objection')], max_length=10)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='board.lead')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
