# Generated by Django 3.1.7 on 2025-07-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_complaint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={},
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='date',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='resolved',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='text',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='type',
        ),
    ]
