# Generated by Django 3.1.7 on 2025-07-23 11:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0028_auto_20250723_1636'),
        ('main', '0005_auto_20250723_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-date'], 'verbose_name': 'Complaint', 'verbose_name_plural': 'Complaints'},
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 11, 36, 25, 152623, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 11, 36, 25, 152571, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='board.lead'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=11, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='type',
            field=models.CharField(choices=[('complaint', 'Complaint'), ('objection', 'Objection')], default='complaint', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
