# Generated by Django 3.1.7 on 2025-07-24 09:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20250723_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 24, 9, 51, 2, 598052, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 24, 9, 51, 2, 597997, tzinfo=utc), verbose_name='Date'),
        ),
    ]
