# Generated by Django 3.1.7 on 2025-07-26 10:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20250724_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 10, 15, 30, 858238, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 10, 15, 30, 858195, tzinfo=utc), verbose_name='Date'),
        ),
    ]
