# Generated by Django 3.1.7 on 2025-07-26 10:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20250726_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 10, 23, 33, 574881, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 10, 23, 33, 574836, tzinfo=utc), verbose_name='Date'),
        ),
    ]
