# Generated by Django 4.2.23 on 2025-07-29 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_calendar_id_alter_complaint_created_at_and_more'),
        ('main', '0009_auto_20250726_1523'),
    ]

    operations = [
    ]
