# Generated by Django 4.2.23 on 2025-07-29 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_merge_20250729_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 7, 41, 0, 109863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 7, 41, 0, 109821, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
