# Generated by Django 3.1.7 on 2025-07-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20250729_1112'),
        ('main', '0016_alter_complaint_created_at_alter_complaint_date'),
    ]

    operations = [
    ]
