# Generated by Django 4.2.23 on 2025-07-31 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_complaint_created_at_alter_complaint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 6, 37, 43, 625199, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 6, 37, 43, 625172, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
