# Generated by Django 3.1.7 on 2025-08-01 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_merge_20250729_1703'),
        ('main', '0018_alter_complaint_created_at_alter_complaint_date'),
    ]

    operations = [
    ]
