# Generated by Django 4.2.23 on 2025-08-01 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_calendar_id_alter_complaint_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 1, 4, 49, 50, 699756, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 1, 4, 49, 50, 699721, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
