# Generated by Django 4.2.23 on 2025-08-01 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_complaint_created_at_alter_complaint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 1, 4, 51, 19, 641068, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 1, 4, 51, 19, 641008, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
    ]
