# Generated by Django 3.1.7 on 2023-04-26 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Tuman',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(default=0)),
                ('finishedPrice', models.IntegerField(default=0)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('companyAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Lead boardda'), (4, "Yo'qotish"), (5, 'Muvaffaqqiyatli yakunlash'), (6, 'Promouter')], default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('finishedDate', models.DateTimeField(blank=True, null=True)),
                ('degree', models.IntegerField(choices=[(1, 'Past'), (2, 'O`rta'), (3, 'Yuqori')], default=1)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('abcxyz', models.CharField(max_length=255, null=True)),
                ('step1', models.TextField(blank=True, default='-', null=True)),
                ('step2', models.TextField(blank=True, default='-', null=True)),
                ('step3', models.TextField(blank=True, default='-', null=True)),
                ('step4', models.TextField(blank=True, default='-', null=True)),
                ('step5', models.TextField(blank=True, default='-', null=True)),
                ('sms_send', models.BooleanField(blank=True, default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('debt', models.IntegerField(default=0)),
                ('joinBy', models.IntegerField(choices=[(0, 'Odatiy'), (1, 'Telegram orqali')], default=0)),
                ('tg_chatid', models.IntegerField(default=0)),
                ('join_from', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('phone2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.district')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Viloyat',
            },
        ),
        migrations.CreateModel(
            name='Telegram_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('companyAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('step', models.IntegerField(choices=[(0, 'Start'), (1, 'Contact'), (2, 'Name'), (3, 'Company'), (4, 'Company Address'), (5, 'Finished')], default=1)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlRedirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('telegram_url', models.URLField(blank=True, editable=False, max_length=400, null=True)),
                ('instagram_url', models.URLField(blank=True, editable=False, max_length=400, null=True)),
                ('facebook_url', models.URLField(blank=True, editable=False, max_length=400, null=True)),
                ('youtube_url', models.URLField(blank=True, editable=False, max_length=400, null=True)),
                ('tiktok_url', models.URLField(blank=True, editable=False, max_length=400, null=True)),
                ('telegram_count', models.BigIntegerField(default=0, editable=False)),
                ('instagram_count', models.BigIntegerField(default=0, editable=False)),
                ('facebook_count', models.BigIntegerField(default=0, editable=False)),
                ('youtube_count', models.BigIntegerField(default=0, editable=False)),
                ('tiktok_count', models.BigIntegerField(default=0, editable=False)),
                ('total_count', models.BigIntegerField(default=0, editable=False)),
                ('next_url', models.URLField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('status', models.IntegerField(choices=[(0, "Ro'yxatga olindi"), (1, 'Bajarilmoqda'), (2, 'Bajarildi'), (3, "O'chirildi")], default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('finishedDate', models.DateTimeField(null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[("Ro'yxatdan o'tish uchun", "Ro'yxatdan o'tish uchun"), ("Tug'ilgan kun", "Tug'ilgan kun"), ('Bayram va boshqalar', 'Bayram va boshqalar')], default="Ro'yxatdan o'tish uchun", max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('text', models.TextField(default='')),
                ('active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('leads', models.ManyToManyField(blank=True, to='board.Lead')),
            ],
        ),
        migrations.CreateModel(
            name='SMSHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=False)),
                ('send_count', models.IntegerField(default=0)),
                ('not_send_count', models.IntegerField(default=0)),
                ('smstemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.smstemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('amount', models.BigIntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.lead')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.payment_type')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.product')),
            ],
        ),
        migrations.CreateModel(
            name='NoteForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('telegram_url', models.URLField(blank=True, editable=False, max_length=400, null=True)),
                ('instagram_url', models.URLField(blank=True, editable=False, max_length=400, null=True)),
                ('facebook_url', models.URLField(blank=True, editable=False, max_length=400, null=True)),
                ('youtube_url', models.URLField(blank=True, editable=False, max_length=400, null=True)),
                ('tiktok_url', models.URLField(blank=True, editable=False, max_length=400, null=True)),
                ('telegram_count', models.BigIntegerField(default=0, editable=False)),
                ('instagram_count', models.BigIntegerField(default=0, editable=False)),
                ('facebook_count', models.BigIntegerField(default=0, editable=False)),
                ('youtube_count', models.BigIntegerField(default=0, editable=False)),
                ('tiktok_count', models.BigIntegerField(default=0, editable=False)),
                ('total_count', models.BigIntegerField(default=0, editable=False)),
                ('image', models.ImageField(upload_to='formImages/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadPoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=-1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
        migrations.CreateModel(
            name='LeadAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Lead yaratildi'), (1, 'Lead taxrirlandi'), (2, "Status o'zgardi"), (3, "Izoh qo'shildi"), (4, "Pole o'zgardi")], default=0)),
                ('oldStatus', models.IntegerField(default=0)),
                ('newStatus', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('color', models.CharField(default='primary', max_length=255)),
                ('changer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.lead')),
                ('newpole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new', to='board.leadpoles')),
                ('oldpole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old', to='board.leadpoles')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='pole',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.leadpoles'),
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.noteform')),
            ],
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('join_by', models.CharField(choices=[('telegram', 'telegram'), ('instagram', 'instagram'), ('facebook', 'facebook'), ('youtube', 'youtube'), ('tiktok', 'tiktok')], default='telegram', max_length=20)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.noteform')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.region'),
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=255)),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.formanswer')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.formquestion')),
            ],
        ),
    ]
