# Generated by Django 3.1.7 on 2023-12-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_lead_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='tg_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
