# Generated by Django 5.0.4 on 2024-04-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_answerquestion_id_alter_categoryproduct_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.IntegerField(choices=[(0, 'Lead boardda'), (1, 'status1'), (4, "Yo'qotish"), (5, 'Muvaffaqqiyatli yakunlash'), (6, 'Promouter')], default=0),
        ),
    ]
