# Generated by Django 5.0.4 on 2024-04-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_leadaction_emotsiya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadaction',
            name='emotsiya',
            field=models.IntegerField(choices=[(1, '🤔 Qarorsiz'), (2, '🤗 Qayta kelishuv'), (3, '😋 Info ehtiyoj'), (4, '🤓 Tasir etish kerak'), (5, '👏🏻 Tezkor sotish kerak'), (6, '🤩 Istemolchi'), (7, '✍🏻 Qo’shimcha kelishuv'), (8, '🙃 Etirozli'), (9, '😖 Shikoyatli')], default=0),
        ),
    ]
