# Generated by Django 3.1.7 on 2025-04-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20240516_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='validity_period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
