# Generated by Django 3.1.7 on 2025-04-28 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_instruktsya'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 17, 16, 46, 750504)),
        ),
    ]
