# Generated by Django 3.1.7 on 2025-04-28 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_instruktsya_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruktsya',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='board_instruktsya_photo/'),
        ),
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 17, 35, 53, 838642)),
        ),
    ]
