# Generated by Django 3.1.7 on 2025-04-30 07:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0012_auto_20250428_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='lead_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.leadaction'),
        ),
        migrations.AddField(
            model_name='task',
            name='lead_status',
            field=models.IntegerField(choices=[(0, 'Yangi'), (1, 'Aloqa'), (2, 'Uchrashuv'), (3, 'Boshqa')], default=0),
        ),
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 12, 7, 3, 229185)),
        ),
    ]
