# Generated by Django 3.1.7 on 2025-04-30 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_auto_20250430_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 12, 7, 21, 348703)),
        ),
    ]
