# Generated by Django 3.1.7 on 2025-04-30 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_auto_20250430_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='lead_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 30, 14, 52, 40, 212105)),
        ),
    ]
