# Generated by Django 3.1.7 on 2025-05-01 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_auto_20250501_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 1, 11, 58, 3, 171756)),
        ),
    ]
