# Generated by Django 3.1.7 on 2025-05-01 07:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_auto_20250501_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.referral'),
        ),
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 1, 12, 24, 20, 265352)),
        ),
    ]
