# Generated by Django 3.1.7 on 2025-05-01 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_auto_20250501_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadaction',
            name='ping',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 1, 16, 45, 16, 78716)),
        ),
    ]
