# Generated by Django 3.1.7 on 2025-05-27 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_auto_20250502_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadpoles',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 27, 23, 44, 38, 703128)),
        ),
    ]
