# Generated by Django 3.1.7 on 2025-07-22 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_auto_20250527_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadpoles',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 22, 13, 39, 10, 329699)),
        ),
    ]
