# Generated by Django 3.1.7 on 2025-07-23 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0027_auto_20250723_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 23, 16, 36, 24, 872135)),
        ),
    ]
