# Generated by Django 3.1.7 on 2025-07-26 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0029_auto_20250724_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 15, 15, 30, 567172)),
        ),
    ]
