# Generated by Django 4.2.23 on 2025-07-29 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0030_alter_answerquestion_id_alter_categoryproduct_id_and_more'),
        ('board', '0031_auto_20250726_1523'),
    ]

    operations = [
    ]
