# Generated by Django 4.2.23 on 2025-07-29 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0032_merge_20250729_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewComplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=355)),
                ('is_bot', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'open'), (2, 'close')], default=1)),
                ('created_add', models.DateTimeField(auto_now_add=True)),
                ('close_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 12, 40, 59, 557003)),
        ),
    ]
