# Generated by Django 4.2.23 on 2025-07-29 07:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0033_newcomplaints_alter_instruktsya_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcomplaints',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.lead'),
        ),
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 12, 42, 13, 157092)),
        ),
    ]
