# Generated by Django 4.2.23 on 2025-07-29 09:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0034_newcomplaints_lead_alter_instruktsya_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 14, 2, 19, 871009)),
        ),
        migrations.AlterField(
            model_name='newcomplaints',
            name='complaint',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='NewObjections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objection', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('created_add', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.lead')),
                ('who_accepted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
