# Generated by Django 4.2.23 on 2025-07-29 09:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0035_alter_instruktsya_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 14, 59, 48, 441644)),
        ),
        migrations.CreateModel(
            name='ClientBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.TextField()),
                ('created_add', models.DateTimeField(auto_now_add=True)),
                ('who_accepted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mijozlar olgan foydalar',
            },
        ),
    ]
