# Generated by Django 4.2.23 on 2025-07-29 10:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0036_alter_instruktsya_date_time_clientbenefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbenefits',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.lead'),
        ),
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 29, 15, 7, 5, 906366)),
        ),
    ]
