# Generated by Django 4.2.23 on 2025-07-30 11:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0038_alter_instruktsya_date_time_whybuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcomplaints',
            name='who_accepted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 16, 49, 52, 23405)),
        ),
    ]
