# Generated by Django 4.2.23 on 2025-07-31 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0039_newcomplaints_who_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='telegram_phone_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 11, 37, 43, 190759)),
        ),
    ]
