# Generated by Django 3.1.7 on 2025-08-01 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0039_merge_20250729_1703'),
        ('board', '0040_lead_telegram_phone_number_and_more'),
    ]

    operations = [
    ]
