# Generated by Django 4.2.23 on 2025-08-01 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0042_alter_answerquestion_id_alter_categoryproduct_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 1, 9, 49, 50, 60758)),
        ),
    ]
