# Generated by Django 4.2.23 on 2025-08-01 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0044_alter_instruktsya_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 1, 9, 56, 18, 257640)),
        ),
    ]
