# Generated by Django 4.2.23 on 2025-08-01 10:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_account_id_alter_card_id_alter_company_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0046_alter_instruktsya_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 1, 15, 36, 18, 374940)),
        ),
        migrations.CreateModel(
            name='LastSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_did', models.CharField(max_length=355)),
                ('created_add', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
    ]
