# Generated by Django 3.1.7 on 2025-09-22 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0048_auto_20250803_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 22, 19, 36, 33, 153430)),
        ),
    ]
