# Generated by Django 3.1.7 on 2025-09-22 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0049_auto_20250922_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 22, 19, 38, 19, 81896)),
        ),
    ]
