# Generated by Django 3.1.7 on 2025-10-14 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0050_auto_20250922_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='investment_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='investment_valuta',
            field=models.IntegerField(choices=[(1, "So'm"), (2, 'Dollar')], default=1),
        ),
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 14, 23, 39, 9, 118871)),
        ),
    ]
