# Generated by Django 3.1.7 on 2025-10-14 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0051_auto_20251014_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='business_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 14, 23, 43, 3, 792316)),
        ),
    ]
