# Generated by Django 3.1.7 on 2026-02-09 13:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0052_auto_20251014_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 9, 18, 39, 57, 825113)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='pole',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.leadpoles'),
        ),
    ]
