# Generated by Django 3.1.7 on 2026-03-12 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0054_auto_20260312_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='servicetype',
            new_name='service_type',
        ),
        migrations.AlterField(
            model_name='instruktsya',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 12, 6, 50, 40, 761775)),
        ),
    ]
